### PR TITLE
Resolve #120: Buried jobs stay buried after a manager restart.

### LINKED ISSUE #120: Buried jobs should not be automatically retried on manager restart
I find current behaviour surprising: consider scenario
- first attempt at job fails creating empty named file
- second attempt fixes problem and puts results in same named file
- manager shutdown and later restarted ready for separate new analysis but previously buried jobs are attempted again overwriting/zeroing the results of the successful jobs.

### PR DESCRIPTION
**Pull request by sb10**
Job buried state is recorded to disk, so that if the manager dies and is
restarted, jobs that were buried remain buried instead of restarting.
(Jobs that were running are not yet handled properly; you still have to kill
all existing runners before restarting the manager, and those jobs start from
scratch.)

queue.Add() and AddMany() can now be told to start an item in the Run or Bury
sub-queues, for queue recovery purposes.

Memory/time/disk learning now only occurs on successful jobs, or those that
failed because they ran out of one of those resources.

Increases to job memory/time/disk due to using too much of one of those now
occur in the ready added callback along with recommendation changes, and the
time increase is fixed to be an hour longer than it took, not an hour longer
than requested. Removed job.updateRecsAfterFailure().

If a job uses more than expected memory and then fails, it is now regarded as
having failed due to memory. (Jobs are still only forcefully killed if they use
up all the machine's memory.)

TestJobqueue() tests split up in to more test functions, to isolate and help
reproduce failures.

### CODE REVIEW

File: queue/queue_test.go [hunk 1]
```diff
@@ -50,7 +50,7 @@ func TestQueue(t *testing.T) {
 				for i := 0; i < 10; i++ {
 					key := fmt.Sprintf("key_%d", i)
 					t := time.Duration((i+1)*100) * time.Millisecond
-					queue.Add(key, "", "data", 0, t, 0*time.Millisecond)
+					queue.Add(key, "", "data", 0, t, 0*time.Millisecond, "")
```
Comment (golangcibot) [inline queue/queue_test.go]: Error return value of `queue.Add` is not checked

File: queue/queue_test.go [hunk 2]
```diff
@@ -71,7 +71,7 @@ func TestQueue(t *testing.T) {
 				for i := 0; i < 10; i++ {
 					key := fmt.Sprintf("key_%d", i)
 					t := time.Duration((i+1)*100) * time.Millisecond
-					queue.Add(key, "", "data", 0, 0*time.Millisecond, t)
+					queue.Add(key, "", "data", 0, 0*time.Millisecond, t, "")
```
Comment (golangcibot) [inline queue/queue_test.go]: Error return value of `queue.Add` is not checked

File: queue/queue_test.go [hunk 3]
```diff
@@ -582,8 +582,8 @@ func TestQueue(t *testing.T) {
 				Convey("Touching doesn't mess with the correct queue order", func() {
 					queue = New("new queue")
 					defer queue.Destroy()
-					queue.Add("item1", "", "data", 0, 0*time.Millisecond, 50*time.Millisecond)
-					queue.Add("item2", "", "data", 0, 0*time.Millisecond, 52*time.Millisecond)
+					queue.Add("item1", "", "data", 0, 0*time.Millisecond, 50*time.Millisecond, "")
```
Comment (golangcibot) [inline queue/queue_test.go]: Error return value of `queue.Add` is not checked

File: queue/queue_test.go [hunk 4]
```diff
@@ -882,6 +882,32 @@ func TestQueue(t *testing.T) {
 		})
 	})
 
+	Convey("You can add items to the queue that start in the run or bury sub-queues", t, func() {
+		queue := New("run/bury queue")
+		defer queue.Destroy()
```
Comment (golangcibot) [inline queue/queue_test.go]: Error return value of `queue.Destroy` is not checked

File: queue/queue_test.go [hunk 5]
```diff
@@ -1124,25 +1150,71 @@ func TestQueue(t *testing.T) {
 		})
 	})
 
+	Convey("You can add many items to the queue that start in the run or bury sub-queues, all in one go", t, func() {
+		queue := New("run/bury queue")
+		defer queue.Destroy()
```
Comment (golangcibot) [inline queue/queue_test.go]: Error return value of `queue.Destroy` is not checked
